name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is this bug related to?
      options:
        - "@dyanet/config-aws (core)"
        - "@dyanet/nestjs-config-aws"
        - "@dyanet/nextjs-config-aws"
        - "Multiple packages"
        - "Not sure"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure with '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue.
      render: typescript

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide relevant environment information.
      placeholder: |
        - Node.js version:
        - TypeScript version:
        - Framework version (NestJS/Next.js):
        - AWS SDK version:
        - OS:
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
